openapi: 3.0.1
info:
  title: JavaRestaurant API
  version: 0.1.0
paths:
  # USER
  /user:
    post:
      tags:
        - user
      summary: Create user
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: invlaid username
          content: {}
        "401":
          description: invalid password
          content: {}
      x-codegen-request-body-name: body
  "/user/{username}":
    get:
      tags:
        - user
      summary: Get user by user name
      operationId: getUserByName
      parameters:
        - name: username
          in: path
          description: "The name that needs to be fetched. Use user1 for testing. "
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/User"
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid username supplied
          content: {}
        "404":
          description: User not found
          content: {}
    put:
      tags:
        - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - name: username
          in: path
          description: name that need to be updated
          required: true
          schema:
            type: string
      requestBody:
        description: Updated user object
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: Invalid user supplied
          content: {}
        "404":
          description: User not found
          content: {}
      x-codegen-request-body-name: body
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - name: username
          in: path
          description: The name that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: Invalid username supplied
          content: {}
        "404":
          description: User not found
          content: {}
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      operationId: loginUser
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
        "400":
          description: Invalid username/password supplied
          content: {}
  /user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        default:
          description: successful operation
          content: {}
  # MEAL
  /meal:
    get:
      tags:
        - meal
      summary: Get meal by {meal name + restaurant name} or {meal id}
      operationId: getMeal
      parameters:
        - name: mealName
          in: query
          description: "The name that needs to be fetched."
          schema:
            type: string
        - name: restaurantName
          in: query
          description: "name of restaurant that serves that meal"
          schema:
            type: string
        - name: mealID
          in: query
          description: "ID of meal to fetch instead of name"
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Meal"
            application/json:
              schema:
                $ref: "#/components/schemas/Meal"
        "404":
          description: Meal not found
          content: {}
    post:
      tags:
        - meal
      summary: Create meal
      description: Should only be carried by restaurant owner, and be logged in
      operationId: createMeal
      requestBody:
        description: Created meal object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Meal"
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: not logged in/ not restaurant owner
          content: {}
        "401":
          description: invalid data
          content: {}
      x-codegen-request-body-name: body
    put:
      tags:
        - meal
      summary: Update meal
      description: This can only be done by the logged in user. and be a restaurant owner
      operationId: updateMeal
      parameters:
        - name: mealName
          in: query
          description: "The name that needs to be fetched."
          schema:
            type: string
        - name: restaurantName
          in: query
          description: "name of restaurant that serves that meal"
          schema:
            type: string
        - name: mealID
          in: query
          description: "ID of meal to fetch instead of name"
          schema:
            type: integer
      requestBody:
        description: Updated meal object
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/Meal"
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: Invalid meal supplied
          content: {}
        "401":
          description: Not logged in
          content: {}
        "404":
          description: Meal not found
          content: {}
      x-codegen-request-body-name: body
    delete:
      tags:
        - meal
      summary: delete meal
      description: This can only be done by the logged in user. and be a restaurant owner
      operationId: deleteMeal
      parameters:
        - name: mealName
          in: query
          description: "The name that needs to be fetched."
          schema:
            type: string
        - name: restaurantName
          in: query
          description: "name of restaurant that serves that meal"
          schema:
            type: string
        - name: mealID
          in: query
          description: "ID of meal to fetch instead of name"
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: Invalid meal supplied
          content: {}
        "401":
          description: Not logged in
          content: {}
        "404":
          description: Meal not found
          content: {}
      x-codegen-request-body-name: body
  "/meal/order":
    get:
      tags:
        - meal
      summary: Get order by {meal name + restaurant name} or {meal id}
      operationId: getOrder
      parameters:
        - name: mealName
          in: query
          description: "The name that needs to be fetched."
          schema:
            type: string
        - name: restaurantName
          in: query
          description: "name of restaurant that serves that meal"
          schema:
            type: string
        - name: mealID
          in: query
          description: "ID of meal to fetch instead of name"
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Order"
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Order not found
          content: {}
    post:
      tags:
        - meal
      summary: Create order
      operationId: createOrder
      parameters:
        - name: mealName
          in: query
          description: "The name that needs to be fetched."
          schema:
            type: string
        - name: restaurantName
          in: query
          description: "name of restaurant that serves that meal"
          schema:
            type: string
        - name: mealID
          in: query
          description: "ID of meal to fetch instead of name"
          schema:
            type: integer
      requestBody:
        description: Created order object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Meal"
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: not logged in/ not restaurant owner
          content: {}
        "401":
          description: invalid data
          content: {}
      x-codegen-request-body-name: body
    put:
      tags:
        - meal
      summary: Update meal
      description: This can only be done by the logged in user. and be a restaurant owner
      operationId: updateMeal
      parameters:
        - name: mealName
          in: query
          description: "The name that needs to be fetched."
          schema:
            type: string
        - name: restaurantName
          in: query
          description: "name of restaurant that serves that meal"
          schema:
            type: string
        - name: mealID
          in: query
          description: "ID of meal to fetch instead of name"
          schema:
            type: integer
        - name: orderID
          in: query
          description: "ID of order to fetch"
          schema:
            type: integer
      requestBody:
        description: Updated meal object
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/Order"
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: Invalid meal supplied
          content: {}
        "401":
          description: Not logged in
          content: {}
        "404":
          description: Meal not found
          content: {}
      x-codegen-request-body-name: body
    delete:
      tags:
        - meal
      summary: delete order
      operationId: deleteOrder
      parameters:
        - name: mealName
          in: query
          description: "The name that needs to be fetched."
          schema:
            type: string
        - name: restaurantName
          in: query
          description: "name of restaurant that serves that meal"
          schema:
            type: string
        - name: mealID
          in: query
          description: "ID of meal to fetch instead of name"
          schema:
            type: integer
        - name: orderID
          in: query
          description: "ID of order to delete"
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content: {}
        "401":
          description: Not logged in
          content: {}
        "404":
          description: Meal not found
          content: {}
      x-codegen-request-body-name: body
  # CART
  /cart:
    get:
      tags:
        - cart
      summary: Get all orders
      operationId: getCart
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: "#/components/schemas/Order"
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: "#/components/schemas/Order"
        "400":
          description: Not Logged in
          content: {}
    delete:
      tags:
        - cart
      summary: empty the cart
      operationId: deleteCart
      responses:
        "200":
          description: successful operation
          content: {}
        "401":
          description: Not logged in
          content: {}
      x-codegen-request-body-name: body
  /cart/confirm:
    get:
      tags:
        - cart
      summary: Confirm the orders
      description: Should only be carried by restaurant owner, and be logged in
      operationId: confirmCart
      parameters:
        - name: addressID
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: not logged in/ not restaurant owner
          content: {}
        "401":
          description: invalid data
          content: {}
      x-codegen-request-body-name: body
  # RESTAURANT
  /restaruant:
    get:
      tags:
        - restaurant
      summary: Get restaurant by name or byid
      operationId: getMeal
      parameters:
        - name: restaurantName
          in: query
          description: "name of restaurant that serves that meal"
          schema:
            type: string
        - name: restaurantID
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Restaurant"
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
        "404":
          description: Restaurant not found
          content: {}
    post:
      tags:
        - restaurant
      summary: Create restaurant
      description: Should only be carried by restaurant owner, and be logged in
      operationId: createRestaurant
      requestBody:
        description: Created restaurant object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Restaurant"
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: not logged in/ not restaurant owner
          content: {}
        "401":
          description: invalid data
          content: {}
      x-codegen-request-body-name: body
    put:
      tags:
        - restaurant
      summary: Update restaurant
      description: This can only be done by the logged in user. and be a restaurant owner
      operationId: updateRestaurant
      parameters:
        - name: restaurantName
          in: query
          description: "name of restaurant that serves that meal"
          schema:
            type: string
        - name: restaurantID
          in: query
          schema:
            type: integer
      requestBody:
        description: Updated meal object
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/Restaurant"
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: Invalid Restaurant supplied
          content: {}
        "401":
          description: Not logged in
          content: {}
        "404":
          description: Restaurant not found
          content: {}
      x-codegen-request-body-name: body
    delete:
      tags:
        - restaurant
      summary: delete restaurant
      description: This can only be done by the logged in user. and be a restaurant owner
      operationId: deleteRestaurant
      parameters:
        - name: restaurantName
          in: query
          description: "name of restaurant that serves that meal"
          schema:
            type: string
        - name: restaurantID
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content: {}
        "401":
          description: Not logged in
          content: {}
        "404":
          description: Restaurant not found
          content: {}
      x-codegen-request-body-name: body
components:
  schemas:
    User:
      type: object
      properties:
        addresses:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/Address"
        email:
          type: string
        firstname:
          type: string
        id:
          type: integer
        lastname:
          type: string
        password:
          type: string
        phone:
          type: string
        username:
          type: string
        isRestaurantOwner:
          type: boolean
        ownedRestaurants:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Restaurant'
      title: User
    Address:
      type: object
      properties:
        id:
          type: integer
        city:
          type: string
        housenumber:
          type: integer
        street:
          type: string
      title: Address
    Order:
      type: "object"
      properties:
        id:
          type: "integer"
        mealID:
          type: "integer"
        numItems:
          type: "integer"
      title: "Order"
    Restaurant:
      type: "object"
      properties:
        id:
          type: "integer"
        ownerID:
          type: integer
        img:
          type: "string"
        meals:
          type: "array"
          items:
            $ref: "#/components/schemas/Meal"
        name:
          type: "string"
      title: "Restaurant"
    Meal:
      type: "object"
      properties:
        id:
          type: "integer"
        restaurantID:
          type: integer
        img:
          type: "string"
        name:
          type: "string"
        price:
          type: "string"
      title: "Meal"
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
