CREATE TABLE IF NOT EXISTS User (
    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL,
    hashedPassword TEXT NOT NULL,
    phone TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Address (
    userID INT NOT NULL REFERENCES User(ROWID) ON UPDATE CASCADE ON DELETE CASCADE,
    city TEXT NOT NULL,
    street TEXT NOT NULL,
    housenumber INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Restaurant (
    ownerID INT NOT NULL REFERENCES User(ROWID) ON UPDATE CASCADE ON DELETE CASCADE,
    img TEXT DEFAULT NULL,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Meal (
    restaurantID INT NOT NULL REFERENCES Restaurant(ROWID) ON UPDATE CASCADE ON DELETE CASCADE,
    img TEXT DEFAULT NULL,
    name TEXT UNIQUE NOT NULL,
    price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS MealOrder (
    mealID INT NOT NULL REFERENCES Meal(ROWID) ON UPDATE CASCADE ON DELETE CASCADE,
    userID INT NOT NULL REFERENCES User(ROWID) ON UPDATE CASCADE ON DELETE CASCADE,
    numItems INT DEFAULT 1
);
